base_global_planner: global_planner/GlobalPlanner
base_local_planner: dwa_local_planner/DWAPlannerROS

GlobalPlanner/use_dijkstra: true #set false to A*
GlobalPlanner/visualize_potential: true
GlobalPlanner/use_grid_path: false
GlobalPlanner/old_navfn_behavior: false #gaktau

shutdown_costmaps: false

controller_frequency: 5.0 #before 5.0
controller_patience: 3.0

planner_frequency: 0.5
planner_patience: 5.0

oscillation_timeout: 4.0
oscillation_distance: 0.1

conservative_reset_dist: 0.1 #distance from an obstacle at which it will unstuck itself

# http://kaiyuzheng.me/documents/navguide.pdf
cost_factor: 0.55
neutral_cost: 66
lethal_cost: 253

# cost_factor: 1.0
# neutral_cost: 55
# lethal_cost: 253