obstacle_range: 2.5 #are used to indicate the maximum distance that the sensor will read and introduce new information in the costmaps.
raytrace_range: 3.0 #used to clean/clear the costmap and update the free space in it when the robot moves

# The footprint attribute is used to indicate the geometry of the robot to the navigation stack. It is used to
# keep the right distance between the obstacles and the robot, or to find out if the robot can go through a
# door. The inflation_radius attribute is the value given to keep a minimal distance between the geometry of
# the robot and the obstacles.
footprint: [[-0.20,-0.145],[-0.20,0.145],[0.20,0.145],[0.20,-0.145]]
footprint_padding: -0.013

inflation_radius: 0.01
transform_tolerance: 0.5

observation_sources: scan
scan:
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true

map_type: costmap
