DWAPlannerROS: #default yang y nya dibuat 0
  max_trans_vel: 0.1
  min_trans_vel: 0.01 #0.01
  max_vel_trans: 0.1
  min_vel_trans: 0.01 #0.01
  max_vel_x: 0.1
  min_vel_x: 0.91 #0.025
  max_vel_y: 0.01
  min_vel_y: -0.01
  max_rot_vel: 0.5
  min_rot_vel: -0.5
  acc_lim_x: 2.0
  acc_lim_y: 1.0
  acc_lim_theta: 4
  acc_lim_trans: 3.0

  latch_xy_goal_tolerance: true

  prune_plan: false

  xy_goal_tolerance: 0.25 #0.25
  yaw_goal_tolerance: 0.25 #0.1
  trans_stopped_vel: 0.1
  rot_stopped_vel: 0.1
  sim_time: 4.0 #3.0 harusnya >=5.0
  sim_granularity: 0.1
  angular_sim_granularity: 0.1
  
  #from paper
  # path_distance_bias: 32.0
  # goal_distance_bias: 20.0
  # occdist_scale: 0.02

  # default
  path_distance_bias: 34.0
  goal_distance_bias: 24.0
  occdist_scale: 0.05
  twirling_scale: 0.0
  stop_time_buffer: 0.5
  oscillation_reset_dist: 0.03 #in meter default 0.05
  oscillation_reset_angle: 0.2 #in meter default 0.2
  forward_point_distance: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  vx_samples: 20
  vy_samples: 20 #0
  vth_samples: 40

  use_dwa: true
  restore_defaults: true
