
# ASTRO
knee_orientation : "><"
pantograph_leg : false
max_linear_velocity_x : 0.22
max_linear_velocity_y : 0.16
max_angular_velocity_z : 1.6 #0.7
swing_height : 0.010
stance_depth : 0.002
stance_duration : 0.4
nominal_height : 0.10

# knee_orientation : ">>"
# pantograph_leg : false
# max_linear_velocity_x : 0.05
# max_linear_velocity_y : 0.1
# max_angular_velocity_z : 0.4
# swing_height : 0.02 #kalau di alfatih z
# # 0.03
# stance_depth : 0.0005
# stance_duration : 0.25 #kalau di alfatih KECEPATAN (y) /depan
# nominal_height : 0.17 #0.158


# BRUNO
# knee_orientation : ">>"
# pantograph_leg : false
# max_linear_velocity_x : 0.5
# max_linear_velocity_y : 0.25
# max_angular_velocity_z : 1.0
# swing_height : 0.04
# stance_depth : 0.0
# stance_duration : 0.25
# nominal_height : 0.25