<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- <xacro:include filename="$(find hector_sensors_description)/urdf/hokuyo_utm30lx.urdf.xacro" />

    <xacro:hokuyo_utm30lx 
        name="hokuyo" 
        parent="base_link" 
        ros_topic="scan" 
        update_rate="30" 
        ray_count="1040" 
        min_angle="130" 
        max_angle="-130" >
        <origin xyz="0.0 0.0 ${base_z_length / 2 + 0.04}" rpy="0 0 0"/>
    </xacro:hokuyo_utm30lx> -->
    
    <!-- <gazebo reference="hokuyo_frame">
		<material>Gazebo/FlatBlack</material>
	</gazebo> -->


    <gazebo reference="lidar_frame">
      <material>Gazebo/FlatBlack</material>
      <sensor type="ray" name="lds_lfcd_sensor">
	    <pose>0 0 0 0 0 0</pose>
	    <visualize>true</visualize>
	    <update_rate>5</update_rate>
	    <ray>
	      <scan>
	        <horizontal>
	          <samples>360</samples>
	          <resolution>1</resolution>
	          <min_angle>0.0</min_angle>
	          <max_angle>6.28319</max_angle>
	        </horizontal>
	      </scan>
	      <range>
	        <min>0.120</min>
          	<max>10.0</max>
          	<resolution>0.5</resolution>
	      </range>
	      <noise>
	        <type>gaussian</type>
	        <mean>0.0</mean>
	        <stddev>0.01</stddev>
	      </noise>
	    </ray>
	    <plugin name="gazebo_ros_lds_lfcd_controller" filename="libgazebo_ros_laser.so">
          <topicName>scan</topicName>
          <frameName>lidar_frame</frameName>
        </plugin>
      </sensor>
    </gazebo>


    <joint name="scan_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_frame"/>
        <origin xyz="0 0 0.077" rpy="0 0 0"/>
    </joint>

    <link name="lidar_frame">
        <visual>
            <origin xyz="0 0 -0.077" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://oped_description/meshes/ydlidar_x4.dae"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="-0.007 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="0.0315" radius="0.035"/>
            </geometry>
            <material name="dark"/>
        </collision>
        <inertial>
            <mass value="0.001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.000001" ixy="0.0" ixz="0.0"
                     iyy="0.000001" iyz="0.0"
                     izz="0.000001" />
        </inertial>
    </link>

    <gazebo>
        <plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">
            <updateRate>50.0</updateRate>
            <bodyName>imu_link</bodyName>
            <topicName>imu/data</topicName>
            <accelDrift>0.005 0.005 0.005</accelDrift>
            <accelGaussianNoise>0.005 0.005 0.005</accelGaussianNoise>
            <rateDrift>0.005 0.005 0.005 </rateDrift>
            <rateGaussianNoise>0.005 0.005 0.005 </rateGaussianNoise>
            <headingDrift>0.005</headingDrift>
            <headingGaussianNoise>0.005</headingGaussianNoise>
        </plugin>
    </gazebo>

    <link name="imu_link">
        <inertial>
            <mass value="0.001"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-09" ixy="0.0" ixz="0.0" iyy="1e-09" iyz="0.0" izz="1e-09"/>
        </inertial>
    </link>
    <joint name="imu_joint" type="fixed">
        <parent link="base_link" />
        <child link="imu_link" />
    </joint>

    <!-- <xacro:include filename="$(find champ_arm_description)/urdf/champ_arm.urdf.xacro" />
    <xacro:champ_arm parent="base_link">
        <origin xyz="0.07 0.0 ${base_z_length / 2}" rpy="0 0 0"/>
    </xacro:champ_arm> -->
</robot>
