"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 25

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - lf_hip_joint
          - lf_upper_leg_joint
          - lf_lower_leg_joint
          - rf_hip_joint
          - rf_upper_leg_joint
          - rf_lower_leg_joint
          - lh_hip_joint
          - lh_upper_leg_joint
          - lh_lower_leg_joint
          - rh_hip_joint
          - rh_upper_leg_joint
          - rh_lower_leg_joint

      gains:
        lf_hip_joint :       {p: 30.0, d: 0.03, i: 1.5}
        lf_upper_leg_joint : {p: 30.0, d: 0.03, i: 1.5}
        lf_lower_leg_joint : {p: 30.0, d: 0.03, i: 1.5}
        rf_hip_joint :       {p: 30.0, d: 0.03, i: 1.5}
        rf_upper_leg_joint : {p: 30.0, d: 0.03, i: 1.5}
        rf_lower_leg_joint : {p: 30.0, d: 0.03, i: 1.5}
        lh_hip_joint :       {p: 30.0, d: 0.03, i: 1.5}
        lh_upper_leg_joint : {p: 30.0, d: 0.03, i: 1.5}
        lh_lower_leg_joint : {p: 30.0, d: 0.03, i: 1.5}
        rh_hip_joint :       {p: 30.0, d: 0.03, i: 1.5}
        rh_upper_leg_joint : {p: 30.0, d: 0.03, i: 1.5}
        rh_lower_leg_joint : {p: 30.0, d: 0.03, i: 1.5}
    #   gains:
    #     lf_hip_joint :       {p: 7.0, d: 0.03, i: 0.0}
    #     lf_upper_leg_joint : {p: 7.0, d: 0.03, i: 0.0}
    #     lf_lower_leg_joint : {p: 7.0, d: 0.03, i: 0.0}
    #     rf_hip_joint :       {p: 7.0, d: 0.03, i: 0.0}
    #     rf_upper_leg_joint : {p: 7.0, d: 0.03, i: 0.0}
    #     rf_lower_leg_joint : {p: 7.0, d: 0.03, i: 0.0}
    #     lh_hip_joint :       {p: 7.0, d: 0.03, i: 0.0}
    #     lh_upper_leg_joint : {p: 7.0, d: 0.03, i: 0.0}
    #     lh_lower_leg_joint : {p: 7.0, d: 0.03, i: 0.0}
    #     rh_hip_joint :       {p: 7.0, d: 0.03, i: 0.0}
    #     rh_upper_leg_joint : {p: 7.0, d: 0.03, i: 0.0}
    #     rh_lower_leg_joint : {p: 7.0, d: 0.03, i: 0.0}