knee_orientation : ">>"
pantograph_leg : false
max_linear_velocity_x : 0.3
max_linear_velocity_y : 0.2
max_angular_velocity_z : 0.7
swing_height : 0.04
# 0.03
stance_depth : 0.0
stance_duration : 0.15
nominal_height : 0.158