knee_orientation : ">>"
pantograph_leg : false
max_linear_velocity_x : 0.05
max_linear_velocity_y : 0.1
max_angular_velocity_z : 0.4
swing_height : 0.02 #kalau di alfatih z
# 0.03
stance_depth : 0.0005
stance_duration : 0.3 #kalau di alfatih KECEPATAN (y) /depan
nominal_height : 0.17 #0.158