"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 25

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - lf_hip_joint
          - lf_upper_leg_joint
          - lf_lower_leg_joint
          - rf_hip_joint
          - rf_upper_leg_joint
          - rf_lower_leg_joint
          - lh_hip_joint
          - lh_upper_leg_joint
          - lh_lower_leg_joint
          - rh_hip_joint
          - rh_upper_leg_joint
          - rh_lower_leg_joint

      gains:
        lf_hip_joint :       {p: 16.0, d: 0.05, i: 1.3}
        lf_upper_leg_joint : {p: 16.0, d: 0.05, i: 1.3}
        lf_lower_leg_joint : {p: 16.0, d: 0.05, i: 1.3}
        rf_hip_joint :       {p: 16.0, d: 0.05, i: 1.3}
        rf_upper_leg_joint : {p: 16.0, d: 0.05, i: 1.3}
        rf_lower_leg_joint : {p: 16.0, d: 0.05, i: 1.3}
        lh_hip_joint :       {p: 16.0, d: 0.05, i: 1.3}
        lh_upper_leg_joint : {p: 16.0, d: 0.05, i: 1.3}
        lh_lower_leg_joint : {p: 16.0, d: 0.05, i: 1.3}
        rh_hip_joint :       {p: 16.0, d: 0.05, i: 1.3}
        rh_upper_leg_joint : {p: 16.0, d: 0.05, i: 1.3}
        rh_lower_leg_joint : {p: 16.0, d: 0.05, i: 1.3}